### ISSUE TITLE
Possible performance issue with AYA_RCS.SlowUpdate

### ISSUE THREAD

**Issue by JonnyOThan** [linuxgurugamer/AllYAll#16] opened 2024-02-24 14:00 UTC
Someone sent me this profile capture, which shows >2 seconds of time in AYA_RCS.SlowUpdate.  I've seen a few other reports of bad performance and All Y'All was also installed, but I don't have any direct evidence implicating it.

![image](https://github.com/linuxgurugamer/AllYAll/assets/9804078/02537be1-e544-47ee-a01a-b27044c3a35c)

Looking through the recent changes, it doesn't *look* like it should cause this...but it's suspicious.

**Comment by linuxgurugamer** [comment] 2024-02-25 00:05
Need to see the craft file, and the sfs file, it will depend on  how many modules the part has.  Also depends on the size of the vessel, the number of stages, etc.  To make it work properly is intense, which is why it only runs 1/sec.
That profile is also incomplete, is this from a single loop, or is it an aggregate over time?
Would also help to have the system specs

**Comment by JonnyOThan** [comment] 2024-02-25 15:10
This is one frame (see player loop at the top).  I only saw this on one frame in the entire capture, not once every second.  There could be an external cause, but it looks like that related code was just updated in the last version of All Y'All so I thought it could be related.  I don't see anything obviously wrong with the code though.

**Comment by linuxgurugamer** [comment] 2024-02-26 18:05
I would need to see the craft file and the game file to test

**Comment by JonnyOThan** [comment] 2024-02-26 22:56
[allyallperf.zip](https://github.com/linuxgurugamer/AllYAll/files/14412247/allyallperf.zip)

Just got a capture from a different user and their profiler capture shows 15 *seconds* inside AYA_RCS.SlowUpdatr every 33 frames.

**Comment by JonnyOThan** [comment] 2024-02-26 23:51
Oh...so I didn't look at the code very closely before.  I saw the most recent update was a bugfix and assumed the RCS feature had been there for a while.  But I think this is just the wrong architecture for the implementation.  *every* RCS part seems to be running this coroutine, which is doing full vessel analysis.  This should be a vessel module or a singleton addon instead, and it should not need to be this slow (each coroutine cycle for a single partmodule is 2-3 seconds).

And the set of rcs modules could be cached and updated on edge triggers.

**Comment by linuxgurugamer** [comment] 2024-03-06 03:12
Going to be the same issue with the engine, I'll have to look at this.  Would still like to know how big the vessels are which they are running, if you could find out.

**Comment by JonnyOThan** [comment] 2024-03-06 03:30
The zip file here includes the craft file. https://github.com/linuxgurugamer/AllYAll/issues/16#issuecomment-1965477352

**Comment by linuxgurugamer** [comment] 2024-03-06 11:54
I saw, thanks.  He has 192 mods, going to take a while for me to set up an install for this to test

**Comment by linuxgurugamer** [comment] 2024-03-06 11:58
Please ask them to contact me directly, either here or on the forums.

**Comment by StormCircuit** [comment] 2024-03-06 17:21
> Please ask them to contact me directly, either here or on the forums.

Hi, I am one of the users with allya'll lag. I will provide a craft file if I can reproduce it again or let you know if I cannot. In my particular case it was a situation of attaching a subassembly and then attempting to launch it. I tried to narrow down the parts involved but it tentatively seems like anything with an RCS tank. I noticed it occurring outside of this use case however.

That capture (the above capture appears to be mine from my test) was short for my session because, as far as I can tell, allya'll was causing ridiculous frame drops the moment the vehicle was loaded. It may only record 1 frame but thats because only 1 frame was rendered in 5 minutes of letting it sit.

My mod list is about 65 mods long

zip with CKAN: [1.zip](https://github.com/linuxgurugamer/AllYAll/files/14513416/1.zip)

**Comment by linuxgurugamer** [comment] 2024-03-06 19:02
@StormCircuit Thanks, 65 mods is easier than 192 mods

**Comment by fihnakis** [comment] 2024-03-06 20:16
Also one of the users though I have since done a full reinstall. I can install latest version and see if issues persists in this install. Same situation as stormcircuit, almost word for word my issue though obviously double the mod count. 

Just to add, I always knew the craft I was building would have issues with All Y'all once Mechjeb deltaV window would no longer show calculations past the first decoupler / separator.

**Comment by linuxgurugamer** [comment] 2024-03-06 20:45
> Also one of the users though I have since done a full reinstall. I can install latest version and see if issues persists in this install. Same situation as stormcircuit, almost word for word my issue though obviously double the mod count.
> 
> Just to add, I always knew the craft I was building would have issues with All Y'all once Mechjeb deltaV window would no longer show calculations past the first decoupler / separator.

You'res is probably better, if you could zip up the entire KSP GameData directory and get that to me, would make things much easier for me.  Also include the sfs and craft file in the same zip, will just make it easier to keep things organized

If all mods are installed via CKAN, you can start with the .ckan file first, that may be all I need to recreate the install

Just a general comment, in general, this is an expensive operation, given what it needs to do.  You can disable it by  editing the AllYAll.cfg and deleting the first two sections which reference ModuleRCS nad ModuleRCSFX
Once I have the zip, if you can do it, I should be able to figure out how to optimize it better

**Comment by fihnakis** [comment] 2024-03-06 22:11
No problem. I'll reinstall the mod Friday, make sure it's still affecting this new install and if so then will do as requested.

**Comment by JonnyOThan** [comment] 2024-03-06 22:18
> this is an expensive operation, given what it needs to do

Er this should be rebuilt as something other than a PartModule so that each RCS module doesn't have to traverse the entire vessel.

**Comment by linuxgurugamer** [comment] 2024-03-06 23:45
Will be part of my review and rework

**Comment by linuxgurugamer** [comment] 2024-03-07 14:31
> > Please ask them to contact me directly, either here or on the forums.
> 
> Hi, I am one of the users with allya'll lag. I will provide a craft file if I can reproduce it again or let you know if I cannot. In my particular case it was a situation of attaching a subassembly and then attempting to launch it. I tried to narrow down the parts involved but it tentatively seems like anything with an RCS tank. I noticed it occurring outside of this use case however.
> 
> That capture (the above capture appears to be mine from my test) was short for my session because, as far as I can tell, allya'll was causing ridiculous frame drops the moment the vehicle was loaded. It may only record 1 frame but thats because only 1 frame was rendered in 5 minutes of letting it sit.
> 
> My mod list is about 65 mods long
> 
> zip with CKAN: [1.zip](https://github.com/linuxgurugamer/AllYAll/files/14513416/1.zip)

Sadly, your CKAN file didn't contain a list of any mods

**Comment by StormCircuit** [comment] 2024-03-12 16:13
> > > Please ask them to contact me directly, either here or on the forums.
> > 
> > 
> > Hi, I am one of the users with allya'll lag. I will provide a craft file if I can reproduce it again or let you know if I cannot. In my particular case it was a situation of attaching a subassembly and then attempting to launch it. I tried to narrow down the parts involved but it tentatively seems like anything with an RCS tank. I noticed it occurring outside of this use case however.
> > That capture (the above capture appears to be mine from my test) was short for my session because, as far as I can tell, allya'll was causing ridiculous frame drops the moment the vehicle was loaded. It may only record 1 frame but thats because only 1 frame was rendered in 5 minutes of letting it sit.
> > My mod list is about 65 mods long
> > zip with CKAN: [1.zip](https://github.com/linuxgurugamer/AllYAll/files/14513416/1.zip)
> 
> Sadly, your CKAN file didn't contain a list of any mods

Hey, sorry for the slow reply, busy work week. 
[test2.zip](https://github.com/linuxgurugamer/AllYAll/files/14575557/test2.zip)
If that, for whatever reason, does not work:
https://pastebin.com/13dGfrrf

**Comment by linuxgurugamer** [comment] 2024-03-12 16:59
> Hey, sorry for the slow reply, busy work week.
> [test2.zip](https://github.com/linuxgurugamer/AllYAll/files/14575557/test2.zip)

That worked, I have the craft file from a previous zip
Also, your system specs might be helpful

**Comment by linuxgurugamer** [comment] 2024-03-12 17:16
The craft file provided in that allyallperf.zip file isn't loading, there are still some missing parts:
![image](https://github.com/linuxgurugamer/AllYAll/assets/1630166/921ad1bf-0f82-49c4-9470-603816963b6d)

**Comment by linuxgurugamer** [comment] 2024-03-12 17:37
I think I've figured out all the missing mods

**Comment by JonnyOThan** [comment] 2024-03-12 18:05
I'd suspect that this issue will pop up any time you have a lot of rcs thrusters on a high part count ship.

**Comment by linuxgurugamer** [comment] 2024-03-12 18:25
I've been able to replicate the issue

**Comment by linuxgurugamer** [comment] 2024-03-12 18:26
@JonnyOThan Curious what profiler you are using to capture that info

**Comment by JonnyOThan** [comment] 2024-03-12 19:03
@linuxgurugamer it's the unity profiler.  Setup details here: https://gist.github.com/gotmachine/d973adcb9ae413386291170fa346d043

**Comment by linuxgurugamer** [comment] 2024-03-13 02:10
thanks.

Problem has been found, testing now

**Comment by linuxgurugamer** [comment] 2024-03-13 02:18
Fixed in current release

**Closed as completed by linuxgurugamer** 2024-03-13 02:18 UTC

**Comment by KerballOne** [comment] 2024-07-07 04:58
Having major performance issues in 0.11.21
Not sure if it is RCS related... but certainly manifested when part count climbed over 40, particularly when adding RP-1 Apollo LEM to my Saturn V (contains lots of RealismOverhaul part modules including RCS).
[Mods_list.txt](https://github.com/user-attachments/files/16118161/Mods_Realism5.txt)
[Apollo 8.zip](https://github.com/user-attachments/files/16118163/Apollo.8.zip)

**Comment by JonnyOThan** [comment] 2024-07-07 12:30
@KerballOne Unless you have specific information that this RCS issue from AllY'all is related to your performance issue (which you did not include in your comment) it would probably best to post in a generalized support forum or discord somewhere.  And include your ksp.log file.

If you do suspect it is caused by All Y'all, you should try removing it and see if the problem goes away.

**Comment by KerballOne** [comment] 2024-07-10 16:24
Yes, removing All Y'all fixed the problem.  

Several others with the same issue have posted log files here.
https://forum.kerbalspaceprogram.com/topic/155858-19x-all-yall-continued-one-button-common-action-grouping/?do=findComment&comment=4403433

**Comment by JonnyOThan** [comment] 2024-07-31 20:11
Possible data point:  I was looking at someone's logs and noticed this:

```
[LOG 20:17:10.822] [CommNet Constellation] CommNet Vessel 'reMinmus_1' has the single freq 0 of 5000 power
[EXC 20:24:35.782] OutOfMemoryException: Out of memory
    System.Collections.Generic.List`1[T].set_Capacity (System.Int32 value) (at <9577ac7a62ef43179789031239ba8798>:0)
    System.Collections.Generic.List`1[T].EnsureCapacity (System.Int32 min) (at <9577ac7a62ef43179789031239ba8798>:0)
    System.Collections.Generic.List`1[T].InsertRange (System.Int32 index, System.Collections.Generic.IEnumerable`1[T] collection) (at <9577ac7a62ef43179789031239ba8798>:0)
    System.Collections.Generic.List`1[T].AddRange (System.Collections.Generic.IEnumerable`1[T] collection) (at <9577ac7a62ef43179789031239ba8798>:0)
    AllYAll.Extensions.GetAllChildren (Part part, System.Boolean print) (at <d3effebfd4ca4061952bec8aae8a65c7>:0)
    AllYAll.AYA_VesselModule.ProcessDecoupler (ModuleDecouplerBase d, System.Int32 stage) (at <d3effebfd4ca4061952bec8aae8a65c7>:0)
    AllYAll.AYA_VesselModule.GetAllPartsInEachStage () (at <d3effebfd4ca4061952bec8aae8a65c7>:0)
    AllYAll.AYA_VesselModule+<SlowUpdate>c__Iterator0.MoveNext () (at <d3effebfd4ca4061952bec8aae8a65c7>:0)
    UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <12e76cd50cc64cf19e759e981cb725af>:0)
    UnityEngine.DebugLogHandler:LogException(Exception, Object)
    ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
    UnityEngine.MonoBehaviour:StartCoroutine(String)
    AllYAll.AYA_VesselModule:Start()
```

that's over 7 minutes between the previous log message and the out of memory error.  Something weird is going on.

**Comment by linuxgurugamer** [comment] 2024-07-31 20:13
That's old, I've resolved the issue with the latest update (not using SlowUpdate anymore)

**Comment by JonnyOThan** [comment] 2024-07-31 21:32
ah yep, here's their version:

`  AllYAll                                 0.11.21.0                0.11.21                  0.11                     d70cbe11833eb62beb633910a6177f06d8907f9e0189e649683e331d6c082791`
